# Server port
server.port=${PORT:8085}

# Database configuration (Defaults to local H2 database)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./hms-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

# H2 Console configuration (only active when using H2 database)
spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
